export { default as abeg } from "./abeg.png"
export { default as access } from "./access_bank.png"
export { default as bolt } from "./bolt.png"
export { default as first_bank } from "./first_bank.png"
export { default as airtel } from "./airtel.png"
export { default as instagram } from "./instagram.png"
export { default as twitter } from "./twitter.png"
export { default as youtube } from "./youtube.png"